mutation createArgument(
  $missionId: String!
  $providerId: String!
  $missionTplId: String!
  $paramName: String!
  $paramValue: String!
  $paramUnits: String
) {
  createArgument(
    input: {
      argument: {
        missionId: $missionId
        providerId: $providerId
        missionTplId: $missionTplId
        paramName: $paramName
        paramValue: $paramValue
        paramUnits: $paramUnits
      }
    }
  ) {
    argument {
      missionId
      providerId
      missionTplId
      paramName
      paramValue
      paramUnits
    }
  }
}
