mutation updateArgument($input: UpdateArgumentInput!) {
  updateArgument(input: $input) {
    argument {
      missionId
      providerId
      missionTplId
      paramName
      paramValue
      paramUnits
    }
  }
}

# variables: {
#  "input": {
#    "id": "asasasas",
#    "argumentPatch": {
#      "paramValue": "3131"
#    }
#  }
#}
