query assetClass($providerId: String!, $className: String!) {
  assetClass(providerId:$providerId, className: $className) {
    providerId
    provider {
      descriptionFormat
    }
    className
    description
    assets {
      assetId
      description
    }
  }
}
