query asset($providerId:String!, $assetId: String!) {
  asset(providerId: $providerId, assetId: $assetId) {
    assetClass {
      provider {
        descriptionFormat
      }
    }
    assetId
    className
    description
  }
}
