query assetForProvider($providerId: String!) {
  assetsForProvider(providerId: $providerId) {
    providerId
    provider {
      descriptionFormat
    }
    className
    assetId
    description
  }
}
