query assetClassesForProvider($providerId: String!) {
  assetClassesForProvider(providerId: $providerId) {
    providerId
    provider {
      descriptionFormat
    }
    className
    description
  }
}
