query getMissionTplBasic($providerId: String!, $missionTplId: String!) {
  missionTplByProviderIdAndMissionTplId(providerId: $providerId, missionTplId: $missionTplId) {
    id
    missionTplId
    retrievedAt
  }
}
