query getMissionTpl($providerId: String!, $missionTplId: String!) {
  missionTemplate(providerId: $providerId, missionTplId: $missionTplId) {
    provider {
      descriptionFormat
      usesUnits
      usesSched
      canReportMissionStatus
    }
    missionTplId
    description
    retrievedAt
    assetClasses {
      className
      description
    }
    parameters {
      paramName
      type
      valueCanReference
      required
      defaultValue
      defaultUnits
      description
    }
  }
}
