query mission($providerId: String!, $missionTplId: String!, $missionId: String!) {
  mission(providerId: $providerId, missionTplId: $missionTplId, missionId: $missionId) {
    providerId
    missionTplId
    missionId
    missionStatus
    assetId
    schedType
    schedDate
    asset {
      className
    }
    description
    arguments {
      paramName
      paramValue
      paramUnits
    }
    provider {
      httpEndpoint
      apiType
      canValidate
      usesSched
      usesUnits
      canReportMissionStatus
      descriptionFormat
    }
    missionTemplate {
      parameters {
        paramName
        type
        valueCanReference
        required
        defaultValue
        defaultUnits
        description
      }
    }
  }
}
