query missionTplsDirectory($providerId: String!, $directory: String!) {
  listMissionTplsDirectory(providerId: $providerId, directory: $directory) {

    providerId
    provider {
      descriptionFormat
    }
    missionTplId
    description
    assetClasses {
      className
      assets {
        assetId
      }
    }
  }
}
