mutation createMission($pl: MissionInput!) {
  createMission(pl: $pl) {
    providerId
    missionTplId
    missionId
    missionStatus
    assetId
    description
    schedType
    schedDate
    startDate
    endDate
  }
}
