mutation updateMission($pl: MissionInput!) {
  updateMission(pl: $pl) {
    providerId
    missionTplId
    missionId
    missionStatus
    updatedDate
    providerMissionId
    description
    assetId
    startDate
    endDate
  }
}
