query missionsForProvider($providerId: String!) {
  missionsForProvider(providerId: $providerId) {
    providerId
    provider {
      descriptionFormat
    }
    missionTplId
    missionId
    providerMissionId
    updatedDate
    missionStatus
    assetId
    description
    startDate
    endDate
  }
}
