query parameter($providerId: String!, $missionTplId: String!, $paramName: String!) {
  parameter (
    providerId: $providerId,
    missionTplId: $missionTplId,
    paramName: $paramName
  ) {
    providerId
    provider {
      descriptionFormat
    }
    missionTplId
    paramName
    type
    required
    defaultValue
    defaultUnits
    valueCanReference
    description
  }
}
