mutation createProvider($pl: ProviderInput!) {
  createProvider(pl: $pl) {
    providerId
    httpEndpoint
    apiType
    description
    canValidate
    usesUnits
    usesSched
    descriptionFormat
  }
}
