mutation createProvider($input: CreateProviderInput!) {
  createProvider(input: $input) {
    provider {
      providerId
      httpEndpoint
      apiType
      description
      canValidate
      usesUnits
      usesSched
      descriptionFormat
    }
  }
}

#    {
#      "input": {
#        "provider": {
#          "providerId": "x1",
#          "httpEndpoint": "h:/x1",
#          "apiType": "REST0",
#          "description": "...",
#          "canValidate": true,
#          "descriptionFormat": "markdown",
#          "usesUnits": true,
#          "usesSched": false
#        }
#      }
#    }
