query provider($providerId: String!) {
  provider(providerId: $providerId) {
    providerId
    httpEndpoint
    apiType
    description
    canValidate
    canReportMissionStatus
    usesUnits
    usesSched
    descriptionFormat
    missionTemplates {
      missionTplId
      description
      assetClasses {
        className
        assets {
          assetId
        }
      }
      missions {
        missionId
      }
    }
    assetClasses {
      className
      assets {
        assetId
      }
    }
    units {
      unitName
    }
  }
}
