query derivedUnits($providerId: String!, $unitName: String!) {
  unit(
    providerId: $providerId
    unitName: $unitName
  ) {
    providerId
    unitName
    abbreviation
    baseUnit
    derivedUnits {
      unitName
      abbreviation
      baseUnit
    }
  }
}
