name: MXM tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
      - name: Install jest
        run: yarn global add jest
      - name: Build and test
        run: (yarn && npm run test:unit)

#      - uses: act10ns/slack@v1
#        with:
#          status: ${{ job.status }}
#          fields: repo,message,commit,ref,workflow
#          # fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
#        if: always() # Pick up events even if the job fails or is canceled.
